// Build the fig WebAssembly module and inline it into the TypeScript source.
//
// Runs `zig build wasm` at the repository root, then base64-encodes the
// resulting freestanding reactor module into `src/wasm-bytes.ts`. Inlining
// (rather than shipping a separate `.wasm`) keeps the published package a single
// JS payload that loads identically under Node and every bundler, with no
// `fetch`/`fs` path to special-case. The module imports nothing, so it
// instantiates synchronously.
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..", "..", "..");
const srcDir = resolve(here, "..", "src");

// ZON is left out of the default published module. It's the newest editable
// format and the one least likely to be needed by a typical JSON/YAML/TOML/Fig
// consumer, so it's excluded to keep the inlined base64 payload smaller for
// everyone else. Set FIG_WASM_ZON=1 to build a module with it included — that
// module supports ZON editing at full parity with the other formats (see
// docs/typescript.md's Formats section). Either way, check `capabilities()` at
// runtime rather than assuming — don't hard-code which module you're running.
const includeZon = process.env.FIG_WASM_ZON === "1";
// INI/dotenv/.properties/NestedText are `-D<lang>` default-on in build.zig, so
// `zig build wasm` already links them into the published module. plist is
// default-off and left out here too — its XML parser is the heaviest of the
// group and the least likely to be needed by a typical consumer, so (like ZON)
// it's opt-in to keep the inlined base64 payload smaller for everyone else. Set
// FIG_WASM_PLIST=1 to build a module with it included. Either way, check
// `capabilities()` at runtime rather than assuming which module you're running.
const includePlist = process.env.FIG_WASM_PLIST === "1";
const zigArgs = [
  "build",
  "wasm",
  includeZon ? "-Dzon=true" : "-Dzon=false",
  includePlist ? "-Dplist=true" : "-Dplist=false",
];

console.error(`· zig ${zigArgs.join(" ")}`);
execFileSync("zig", zigArgs, { cwd: repoRoot, stdio: "inherit" });

const wasmPath = join(repoRoot, "zig-out", "bin", "fig.wasm");
const wasm = readFileSync(wasmPath);
const base64 = wasm.toString("base64");
console.error(`· fig.wasm ${(wasm.length / 1024).toFixed(1)} KiB → ${(base64.length / 1024).toFixed(1)} KiB base64`);

const banner = `// @generated by scripts/build-wasm.mjs — do not edit by hand.
// The fig core (src/c_api.zig) compiled to a freestanding wasm32 reactor
// module, base64-encoded. Regenerate with \`npm run build:wasm\`.
`;

// Chunk the literal so editors/diff tools don't choke on one multi-hundred-KiB
// line, and emit it as an ARRAY joined at runtime rather than a `"a" + "b" + …`
// expression: a deep `+`-chain is parsed by recursive descent, so a large module
// overflows the stack of Node's lightweight TS type-stripper (and some bundlers).
// An array literal parses flat.
const chunks = [];
for (let i = 0; i < base64.length; i += 120) chunks.push(base64.slice(i, i + 120));
const literal = chunks.map((c) => `  "${c}",`).join("\n");

mkdirSync(srcDir, { recursive: true });
writeFileSync(
  join(srcDir, "wasm-bytes.ts"),
  `${banner}export const WASM_BASE64: string = [\n${literal}\n].join("");\n`,
);
console.error("· wrote src/wasm-bytes.ts");
