//! YAML conformance scoreboard against the yaml-test-suite
//! (https://github.com/yaml/yaml-test-suite).
//!
//! Unlike the JSON harness, which hard-fails on any mismatch, this one is a
//! *scoreboard*: fig's YAML parser is still a subset of 1.2.2, so many accept
//! cases legitimately fail today. Each run prints a tally and asserts the score
//! has not dropped below a recorded baseline, so the numbers ratchet upward and
//! regressions are caught.
//!
//! Fixtures are generated by scripts/gen_yaml_conformance.py, which decodes the
//! suite's whitespace placeholders and excludes out-of-scope tests (anchors,
//! aliases, tags, directives) listed in testdata/yaml/skiplist.txt.
//!
//! Run with: zig build test -Dyaml-conformance=true

const std = @import("std");
const testing = std.testing;

const Parser = @import("parser.zig");
const YamlType = @import("yaml.zig").Type;

const max_fixture_size = 1024 * 1024;

// Baseline scores. These are a ratchet: raise them as coverage improves; never
// lower them without a deliberate reason. A run below baseline fails the test.
const accept_baseline = 116;
const reject_baseline = 65;

const Score = struct {
    correct: usize = 0,
    total: usize = 0,
};

test "yaml conformance: scoreboard" {
    const accept = try scoreDir("testdata/yaml/accept", .should_pass);
    const reject = try scoreDir("testdata/yaml/reject", .should_fail);

    std.debug.print(
        \\
        \\YAML conformance (yaml-test-suite, out-of-scope excluded)
        \\  accept (must parse): {d}/{d}   baseline {d}
        \\  reject (must fail) : {d}/{d}   baseline {d}
        \\
    , .{
        accept.correct, accept.total, accept_baseline,
        reject.correct, reject.total, reject_baseline,
    });

    try testing.expect(accept.correct >= accept_baseline);
    try testing.expect(reject.correct >= reject_baseline);
}

const Expected = enum { should_pass, should_fail };

fn scoreDir(dir_path: []const u8, expected: Expected) !Score {
    var threaded = std.Io.Threaded.init(testing.allocator, .{});
    defer threaded.deinit();
    const io = threaded.io();

    var dir = try std.Io.Dir.cwd().openDir(io, dir_path, .{ .iterate = true });
    defer dir.close(io);

    var score: Score = .{};
    var iterator = dir.iterate();
    while (try iterator.next(io)) |entry| {
        if (entry.kind != .file) continue;
        if (!std.mem.endsWith(u8, entry.name, ".yaml")) continue;

        const input = try dir.readFileAlloc(
            io,
            entry.name,
            testing.allocator,
            .limited(max_fixture_size),
        );
        defer testing.allocator.free(input);

        score.total += 1;
        const parsed = Parser.parse(testing.allocator, input, YamlType.v1_2_2);
        switch (expected) {
            .should_pass => {
                if (parsed) |doc| {
                    var d = doc;
                    d.deinit(testing.allocator);
                    score.correct += 1;
                } else |_| {}
            },
            .should_fail => {
                if (parsed) |doc| {
                    var d = doc;
                    d.deinit(testing.allocator);
                } else |_| {
                    score.correct += 1;
                }
            },
        }
    }
    return score;
}
